// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./App.vue')['default']
    DarkModeSwitch: typeof import('./DarkModeSwitch.vue')['default']
    'DarkModeSwitch.ce': typeof import('./node_modules/@mussi/vue-custom-element-example/src/DarkModeSwitch.ce.vue')['default']
    'GithubLink.ce': typeof import('./node_modules/@mussi/vue-custom-element-example/src/GithubLink.ce.vue')['default']
    'Ic:TwotoneNightlight': typeof import('~icons/ic/-twotone-nightlight')['default']
    'Ic:TwotoneWbSunny': typeof import('~icons/ic/-twotone-wb-sunny')['default']
    IcTwotoneNightlight: typeof import('~icons/ic/twotone-nightlight')['default']
    IcTwotoneWbSunny: typeof import('~icons/ic/twotone-wb-sunny')['default']
    NotoFullMoon: typeof import('~icons/noto/full-moon')['default']
    NotoFullMoonFace: typeof import('~icons/noto/full-moon-face')['default']
    NotoSun: typeof import('~icons/noto/sun')['default']
    NotoSunWithFace: typeof import('~icons/noto/sun-with-face')['default']
  }
}
