// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Ic:twotoneNightlight': typeof import('~icons/ic/twotone-nightlight')['default']
    'Ic:twotoneWbSunny': typeof import('~icons/ic/twotone-wb-sunny')['default']
    'Mdi:github': typeof import('~icons/mdi/github')['default']
  }
}
